language: php
sudo: false

cache:
    directories:
      - $HOME/.composer/cache

php: 
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then rm phpspec.yml.dist; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require --no-update --dev henrikbjorn/phpspec-code-coverage; fi;'
  - composer update
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then php bin/typehint-to-docblock transform spec; fi;'
after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'

script: composer test
